version: 1.0.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- ps: dotnet restore rules-framework.sln
- ps: dotnet build rules-framework.sln --no-restore
- ps: dotnet pack src/Rules.Framework/Rules.Framework.csproj --no-build --include-symbols
test_script:
- ps: dotnet test tests/Rules.Framework.Tests --no-build
- ps: dotnet test tests/Rules.Framework.IntegrationTests --no-build
deploy:
- provider: NuGet
  server: https://www.nuget.org
  api_key:
    secure: 7Oxxk5PLf3+3rZSSqpjRS7DogIQi9E3ipeMw0ACOTHhVtLE2aLzn7OT9/+vnumjb
  skip_symbols: false
  symbol_server: https://nuget.smbsrc.net/
  artifact: Rules.Framework.$(appveyor_build_version).nupkg
notifications:
- provider: Email
  to:
  - luis_garces@live.com.pt
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false