version: 1.0.{build}
skip_commits:
  message: /docs:/
image: Ubuntu
skip_branch_with_pr: true
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
services: mongodb
install:
  - sh: dotnet tool install --global dotnet-sonarscanner
  - sh: dotnet tool install --global dotnet-reportgenerator-globaltool
  - sh: sudo update-alternatives --query java
  - sh: sudo update-alternatives --auto java
  - sh: export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/
  - sh: export PATH=$PATH:$JAVA_HOME
before_build:
  - sh: dotnet sonarscanner begin /k:pikenikes_rules-framework /v:$APPVEYOR_BUILD_VERSION /o:pikenikes-github /d:sonar.host.url=https://sonarcloud.io /d:sonar.login=8f9e9412fb5ebcf5ea6f9a6b285b288e4645f866 /d:sonar.coverage.exclusions="tests/*Tests/**" /d:sonar.coverageReportPaths="../../coverage-outputs/SonarQube.xml" /d:sonar.branch.name=$APPVEYOR_REPO_BRANCH
build_script:
  - sh: dotnet restore rules-framework.sln --no-cache
  - sh: dotnet build rules-framework.sln --no-restore
  - sh: dotnet pack src/Rules.Framework/Rules.Framework.csproj --no-build --include-symbols
  - sh: dotnet pack src/Rules.Framework.Providers.MongoDb/Rules.Framework.Providers.MongoDb.csproj --no-build --include-symbols
  - sh: dotnet pack src/Rules.Framework.Providers.InMemory/Rules.Framework.Providers.InMemory.csproj --no-build --include-symbols
test_script:
  - sh: dotnet test rules-framework.sln --no-build --collect:"XPlat Code Coverage" --results-directory:"../../coverage-outputs" -m:1
  - sh: reportgenerator -reports:"../../coverage-outputs/**/*.xml" -targetdir:"../../coverage-outputs" -reporttypes:SonarQube
  - sh: rm -rfv ../../coverage-outputs/*/
  - sh: ls -la ../../coverage-outputs
after_test:
  - sh: dotnet sonarscanner end /d:sonar.login=8f9e9412fb5ebcf5ea6f9a6b285b288e4645f866
artifacts:
- path: '**/*.nupkg'
  name: NuGetPackages
deploy:
- provider: NuGet
  api_key:
    secure: kWutFj0HSiu1hDXHcYc3dKVJFeW5ZX+Oj2SDvP4IvAooGK98f3qXpWlAEq7swAFC
  skip_symbols: true
  symbol_server: https://nuget.smbsrc.net/
  artifact: /.*\.nupkg/
  on:
    branch: master
notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false