version: 1.0.{build}
image: Ubuntu
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
  - sh: dotnet tool install --global dotnet-sonarscanner
before_build:
  - sh: dotnet sonarscanner begin /k:pikenikes_rules-framework /v:$APPVEYOR_BUILD_VERSION /o:pikenikes-github /d:sonar.host.url=https://sonarcloud.io /d:sonar.login=8f9e9412fb5ebcf5ea6f9a6b285b288e4645f866 /d:sonar.coverage.exclusions="tests/*Tests/**" /d:sonar.cs.opencover.reportsPaths="*.opencover.xml"
build_script:
  - sh: dotnet restore rules-framework.sln --no-cache
  - sh: dotnet build rules-framework.sln --no-restore
  - sh: dotnet pack src/Rules.Framework/Rules.Framework.csproj --no-build --include-symbols
test_script:
  - sh: dotnet test tests/Rules.Framework.Tests --no-build /p:CollectCoverage=true /p:CoverletOutputFormat="opencover" /p:CoverletOutput=../../tests-coverage
  - sh: dotnet test tests/Rules.Framework.IntegrationTests --no-build /p:CollectCoverage=true /p:CoverletOutputFormat="opencover" /p:CoverletOutput=../../integration-tests-coverage
after_test:
  - sh: dotnet sonarscanner end /d:sonar.login=8f9e9412fb5ebcf5ea6f9a6b285b288e4645f866
artifacts:
- path: '**/*.nupkg'
  name: NuGetPackages
deploy:
- provider: NuGet
  api_key:
    secure: cG3wX34IgH0rZS3vCTrlP6GLi9yineCNh2yGalO2JEINY0XRyNrXHINl0MwHFzIw
  skip_symbols: false
  symbol_server: https://nuget.smbsrc.net/
  artifact: /.*\.nupkg/
  on:
    branch: master
notifications:
- provider: Email
  to:
  - luis_garces@live.com.pt
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false