// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Rules.Framework.SqlServer.Models
{
    // ConditionNodeTypes
    public class ConditionNodeTypeConfiguration : IEntityTypeConfiguration<ConditionNodeType>
    {
        public void Configure(EntityTypeBuilder<ConditionNodeType> builder)
        {
            builder.ToTable("ConditionNodeTypes", "dbo");
            builder.HasKey(x => x.Code).HasName("PK_ConditionNodeTypes").IsClustered();

            builder.Property(x => x.Code).HasColumnName(@"Code").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
        }
    }

}
// </auto-generated>
