// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Rules.Framework.SqlServer.Models
{
    // ConditionTypes
    public class ConditionTypeConfiguration : IEntityTypeConfiguration<ConditionType>
    {
        public void Configure(EntityTypeBuilder<ConditionType> builder)
        {
            builder.ToTable("ConditionTypes", "dbo");
            builder.HasKey(x => x.ConditionTypeCode).HasName("PK_ConditionTypes").IsClustered();

            builder.Property(x => x.ConditionTypeCode).HasColumnName(@"ConditionTypeCode").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
        }
    }

}
// </auto-generated>
