// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Rules.Framework.SqlServer.Models
{
    // ContentTypes
    public class ContentTypeConfiguration : IEntityTypeConfiguration<ContentType>
    {
        public void Configure(EntityTypeBuilder<ContentType> builder)
        {
            builder.ToTable("ContentTypes", "dbo");
            builder.HasKey(x => x.Code).HasName("PK_ContentTypes").IsClustered();

            builder.Property(x => x.Code).HasColumnName(@"Code").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
        }
    }

}
// </auto-generated>
