// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Rules.Framework.SqlServer.Models
{
    // LogicalOperators
    public class LogicalOperatorConfiguration : IEntityTypeConfiguration<LogicalOperator>
    {
        public void Configure(EntityTypeBuilder<LogicalOperator> builder)
        {
            builder.ToTable("LogicalOperators", "dbo");
            builder.HasKey(x => x.Code).HasName("PK_LogicalOperators").IsClustered();

            builder.Property(x => x.Code).HasColumnName(@"Code").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.Symbol).HasColumnName(@"Symbol").HasColumnType("nvarchar(50)").IsRequired().HasMaxLength(50);
        }
    }

}
// </auto-generated>
