// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Rules.Framework.SqlServer.Models
{
    // Operators
    public class OperatorConfiguration : IEntityTypeConfiguration<Operator>
    {
        public void Configure(EntityTypeBuilder<Operator> builder)
        {
            builder.ToTable("Operators", "dbo");
            builder.HasKey(x => x.Code).HasName("PK_Operators").IsClustered();

            builder.Property(x => x.Code).HasColumnName(@"Code").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(100)").IsRequired().HasMaxLength(100);
            builder.Property(x => x.Symbol).HasColumnName(@"Symbol").HasColumnType("nvarchar(20)").IsRequired().HasMaxLength(20);
        }
    }

}
// </auto-generated>
