// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Rules.Framework.SqlServer.Models
{
    // ConditionTypes
    public class ConditionType
    {
        public int ConditionTypeCode { get; set; } // ConditionTypeCode (Primary key)
        public string Name { get; set; } // Name (length: 100)

        // Reverse navigation

        /// <summary>
        /// Child ConditionNodes where [ConditionNodes].[ConditionTypeCode] point to this entity (FK_ConditionNodes_ConditionTypes)
        /// </summary>
        public virtual ICollection<ConditionNode> ConditionNodes { get; set; } // ConditionNodes.FK_ConditionNodes_ConditionTypes

        public ConditionType()
        {
            ConditionNodes = new List<ConditionNode>();
        }
    }

}
// </auto-generated>
