// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Rules.Framework.SqlServer.Models
{
    // ConditionNodeRelations
    public class ConditionNodeRelation
    {
        public long OwnerId { get; set; } // OwnerId (Primary key)
        public long ChildId { get; set; } // ChildId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent ConditionNode pointed by [ConditionNodeRelations].([ChildId]) (FK_ChildConditionNodeRelations_ConditionNodes)
        /// </summary>
        public virtual ConditionNode Child { get; set; } // FK_ChildConditionNodeRelations_ConditionNodes

        /// <summary>
        /// Parent ConditionNode pointed by [ConditionNodeRelations].([OwnerId]) (FK_OwnerConditionNodeRelations_ConditionNodes)
        /// </summary>
        public virtual ConditionNode Owner { get; set; } // FK_OwnerConditionNodeRelations_ConditionNodes
    }

}
// </auto-generated>
