// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Rules.Framework.SqlServer.Models
{
    // ContentTypes
    public class ContentType
    {
        public int Code { get; set; } // Code (Primary key)
        public string Name { get; set; } // Name (length: 100)

        // Reverse navigation

        /// <summary>
        /// Child Rules where [Rules].[ContentTypeCode] point to this entity (FK_Rules_ContentTypes)
        /// </summary>
        public virtual ICollection<Rule> Rules { get; set; } // Rules.FK_Rules_ContentTypes

        public ContentType()
        {
            Rules = new List<Rule>();
        }
    }

}
// </auto-generated>
