// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Rules.Framework.SqlServer.Models
{
    // Operators
    public class Operator
    {
        public int Code { get; set; } // Code (Primary key)
        public string Name { get; set; } // Name (length: 100)
        public string Symbol { get; set; } // Symbol (length: 20)

        // Reverse navigation

        /// <summary>
        /// Child ConditionNodes where [ConditionNodes].[OperatorCode] point to this entity (FK_ConditionNodes_Operators)
        /// </summary>
        public virtual ICollection<ConditionNode> ConditionNodes { get; set; } // ConditionNodes.FK_ConditionNodes_Operators

        public Operator()
        {
            ConditionNodes = new List<ConditionNode>();
        }
    }

}
// </auto-generated>
