// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Rules.Framework.SqlServer.Models
{
    // Rules
    public class Rule
    {
        public long Id { get; set; } // Id (Primary key)
        public string Content { get; set; } // Content (length: 100)
        public int ContentTypeCode { get; set; } // ContentTypeCode
        public DateTime DateBegin { get; set; } // DateBegin
        public DateTime? DateEnd { get; set; } // DateEnd
        public string Name { get; set; } // Name (length: 250)
        public int Priority { get; set; } // Priority
        public long? ConditionNodeId { get; set; } // ConditionNodeId

        // Foreign keys

        /// <summary>
        /// Parent ConditionNode pointed by [Rules].([ConditionNodeId]) (FK_Rules_ConditionNodes)
        /// </summary>
        public virtual ConditionNode ConditionNode { get; set; } // FK_Rules_ConditionNodes

        /// <summary>
        /// Parent ContentType pointed by [Rules].([ContentTypeCode]) (FK_Rules_ContentTypes)
        /// </summary>
        public virtual ContentType ContentType { get; set; } // FK_Rules_ContentTypes
    }

}
// </auto-generated>
