// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore.Design;

namespace Rules.Framework.SqlServer.Models
{
    public class RulesFrameworkDbContextFactory : IDesignTimeDbContextFactory<RulesFrameworkDbContext>
    {
        public RulesFrameworkDbContext CreateDbContext(string[] args)
        {
            return new RulesFrameworkDbContext();
        }
    }
}
// </auto-generated>
