blank_issues_enabled: false
contact_links:
  - name: Documentation 📚
    url: https://github.com/Farfetch/rules-framework#using-the-framework
    about: Check out the official docs for answers to common questions
