name: .NET publish

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      BUILD_VERSION: ${{ github.event.release.tag_name }}

    steps:
    - uses: actions/checkout@2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Update project version
      uses: roryprimrose/set-vs-sdk-project-version@v1
      with:
        projectFilter: '*.csproj'
        version: ${{ env.BUILD_VERSION }}
        assemblyVersion: ${{ env.BUILD_VERSION }}
        fileVersion: ${{ env.BUILD_VERSION }}
        informationalVersion: ${{ env.BUILD_VERSION }}

    - name: Pack Rules.Framework
      run: dotnet pack src/Rules.Framework/Rules.Framework.csproj --include-symbols
      
    - name: Pack Rules.Framework.Providers.MongoDb
      run: dotnet pack src/Rules.Framework.Providers.MongoDb/Rules.Framework.Providers.MongoDb.csproj --include-symbols
      
    - name: Pack Rules.Framework.Providers.InMemory
      run: dotnet pack src/Rules.Framework.Providers.InMemory/Rules.Framework.Providers.InMemory.csproj --include-symbols
        
    - name: Publish NuGet packages
      uses: dansiegel/publish-nuget@v1.01
      with:
        filename: '**/*.nupkg'
        apiKey: ${{ secrets.NUGET_API_KEY }}