name: .NET build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          3.1.x
          6.0.x
        dotnet-quality: ga
    - name: Setup Report Generator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool
    - name: MongoDB in GitHub Actions
      uses: supercharge/mongodb-github-action@1.9.0
      with:
        mongodb-version: '4.4'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    # Gemerate code coverage reports, which are recovered by Codacy afterwards.
    - name: Test
      run: dotnet test --no-build --verbosity normal -m:1 -c Release --collect:"XPlat Code Coverage" --results-directory:"../../coverage-outputs"
    - name: Merge coverage results
      run: |
        reportgenerator -reports:"../../coverage-outputs/**/*.xml" -targetdir:"../../coverage-outputs" -reporttypes:Cobertura
        rm -rfv ../../coverage-outputs/*/
        ls -la ../../coverage-outputs
